services:
  
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/createDB.sql:/docker-entrypoint-initdb.d/database-seed.sql
    expose:
      - 5432
    restart: always
    healthcheck:
      test: >
        psql -U postgres
      interval: ${HC_INTERVAL}
      timeout: ${HC_TIMEOUT}
      retries: ${HC_RETRIES}

  app:
    build: ./app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - .env