services:
  app:
    build: ./app
    depends_on:
      - db
    ports:
      - "3000:3000"
  
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/createDB.sql:/docker-entrypoint-initdb.d/database-seed.sql
    expose:
      - 5432
    restart: always