services:
  
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db/createDB.sql:/docker-entrypoint-initdb.d/database-seed.sql
    restart: always
    healthcheck:
      test: >
        psql -U postgres
      interval: ${HC_INTERVAL}
      timeout: ${HC_TIMEOUT}
      retries: ${HC_RETRIES}

  app:
    build: ./app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
  
  nginx:
    build: ./nginx
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - app

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
      - "${PGADMIN_HTTPS_PORT}:443"