GRANT SELECT, INSERT, DELETE ON saves TO app;
GRANT SELECT, INSERT ON events TO app;
GRANT SELECT, INSERT, DELETE ON event_to_event TO app;
GRANT SELECT, INSERT, DELETE ON event_to_and TO app;
GRANT SELECT, INSERT, DELETE ON event_to_or TO app;